// client/react/src/libs/feature-shell/authenticated-app/pages/homepage.tsx
import moment from "moment";
import { hotelRoom } from "public/assets";
import { styles } from "public/styles";
import { useEffect, useRef, useState } from "react";
import { DateRangePicker } from "react-date-range";
import { useForm } from "react-hook-form";
import { toast } from "react-toastify";
import { useOnClickOutside } from "usehooks-ts";
import { useBnbs } from "../../../feature-data-access-api/bnb";
import { useCreateReservation } from "../../../feature-data-access-api/reservation";
import { BnbType, BnbsSearchType } from "../../../utils/types";
import { Button } from "../../unauthenticated-app/components/button";
import { HomepageHero, Navbar } from "../components";

export const Homepage = () => {
  const [searchCriteria, setSearchCriteria] = useState<BnbsSearchType>({});
  const [bookMeModalOpen, setBookMeModalOpen] = useState(false);
  const [selectedBnb, setSelectedBnb] = useState<BnbType | null>(null);
  const { data: bnbs } = useBnbs(searchCriteria);
  const { handleSubmit } = useForm();
  const [startDate, setStartDate] = useState(new Date());
  const [endDate, setEndDate] = useState(new Date());
  const modalRef = useRef(null);
  const {
    mutate: createReservation,
    status,
    isPending: isCreateReservationPending,
  } = useCreateReservation();

  useEffect(() => {
    if (status === "success") {
      setBookMeModalOpen(false);
      toast.success("Reservation created successfully!");
      setSelectedBnb(null);
      setStartDate(new Date());
      setEndDate(new Date());
    } else if (status === "error") {
      toast.error("Creating reservation error!");
    }
  }, [status]);

  const onSubmit = async () => {
    if (!selectedBnb) return;
    await createReservation({
      start_date: startDate.toISOString().split("T")[0],
      end_date: endDate.toISOString().split("T")[0],
      bnb_id: String(selectedBnb._id),
    });
  };

  const handleSearch = (searchParams: BnbsSearchType) => {
    setSearchCriteria(searchParams);
  };

  const handleBookMeClicked = (bnb: BnbType) => {
    setBookMeModalOpen(true);
    setSelectedBnb(bnb);
  };

  useOnClickOutside(modalRef, () => {
    setBookMeModalOpen(false);
  });

  const handleSelect = (date) => {
    setStartDate(date.selection.startDate);
    setEndDate(date.selection.endDate);
  };

  const selectionRange = {
    startDate: startDate,
    endDate: endDate,
    key: "selection",
  };

  return (
    <>
      <div className="relative bg-black">
        <Navbar />
        <HomepageHero onSearch={handleSearch} />
        <img
          src={hotelRoom}
          className="w-screen h-screen object-cover object-bottom opacity-50"
        />
      </div>
      <div className="bg-white p-5 md:p-10">
        <p className={styles.heading}>All Hotels</p>
        <div className="flex flex-col space-y-2 pt-5">
          {bnbs?.map((bnb: BnbType, index: number) => (
            <div
              key={index}
              className={`grid gap-2 grid-cols-[5fr_1fr] place-items-center justify-items-end ${
                index !== bnbs?.length - 1 && "border-b border-stone-200"
              }`}
            >
              <div className="py-1 grid gap-2 grid-cols-[4fr_2fr_2fr_2fr] w-full">
                <div className="flex flex-col">
                  <p className={`${styles.paragraph2} text-stone-400`}>
                    Address
                  </p>
                  <p className={styles.paragraph}>{bnb?.address}</p>
                </div>
                <div className="flex flex-col">
                  <p className={`${styles.paragraph2} text-stone-400`}>Space</p>
                  <p className={styles.paragraph}>
                    {bnb?.space} m<sup>2</sup>
                  </p>
                </div>
                <div className="flex flex-col">
                  <p className={`${styles.paragraph2} text-stone-400`}>Cost</p>
                  <p className={styles.paragraph}>{bnb?.cost} pln/night</p>
                </div>
                <div className="flex flex-col">
                  <p className={`${styles.paragraph2} text-stone-400`}>
                    Updated
                  </p>
                  <p className={styles.paragraph}>
                    {moment(bnb?.updatedAt).fromNow()}
                  </p>
                </div>
              </div>
              <Button
                variant="primary-inverted"
                onClick={() => handleBookMeClicked(bnb)}
              >
                Book me!
              </Button>
            </div>
          ))}
          {bookMeModalOpen && (
            <div
              ref={modalRef}
              className="p-5 bg-white rounded-lg fixed z-20 top-1/2 left-1/2 transform -translate-y-1/2 -translate-x-1/2 shadow-background"
            >
              <p className={`${styles.heading} pb-2.5`}>Create reservation</p>
              <form onSubmit={handleSubmit(onSubmit)}>
                <div className="flex flex-col space-y-2.5">
                  <p className={styles.paragraph2}>Date (start/end)</p>
                  <DateRangePicker
                    date={new Date()}
                    minDate={new Date()}
                    maxDate={
                      new Date(new Date().setDate(new Date().getDate() + 90))
                    }
                    ranges={[selectionRange]}
                    onChange={handleSelect}
                    rangeColors={["#FF5A5F"]}
                  />
                  <Button isLoading={isCreateReservationPending}>
                    Confirm reservation
                  </Button>
                </div>
              </form>
            </div>
          )}
        </div>
      </div>
    </>
  );
};

// client/vue/src/libs/feature-shell/authenticated-app/pages/homepage.vue
<script setup lang="ts">
import { hotelRoom, styles } from "@firebnb/public";
import { twMerge } from "tailwind-merge";
import { ref, reactive, watch } from "vue";
import { BnbType, BnbsSearchType, DateRangeType } from "../../../utils/types/bnb";
import { useCreateReservation } from "../../../feature-data-access-api/reservation";
import { useBnbs } from "../../../feature-data-access-api/bnb";
import { toast } from "vue3-toastify";
import moment from "moment";
import { onClickOutside } from "@vueuse/core";
import HomepageHero from "../components/homepage-hero.vue";
import Navbar from "../components/navbar.vue";
import Button from "../../unauthenticated-app/components/button.vue";

let searchCriteria = reactive<BnbsSearchType>({});

const bookMeModalOpen = ref(false);
const selectedBnb = ref<BnbType | null>(null);
const dateRange = reactive({
  startDate: new Date(),
  endDate: new Date(),
});
const modalRef = ref();
const { data: bnbs } = useBnbs(searchCriteria);
const {
  mutate: createReservation,
  status,
  isPending: isCreateReservationPending,
} = useCreateReservation();

watch(
  () => status.value,
  (newStatus) => {
    if (newStatus === "success") {
      bookMeModalOpen.value = false;
      toast.success("Reservation created successfully!");
      selectedBnb.value = null;
      dateRange.startDate = new Date();
      dateRange.endDate = new Date();
    } else if (newStatus === "error") {
      toast.error("Creating reservation error!");
    }
  }
);

const onSubmit = async () => {
  if (!selectedBnb) return;
  console.log(dateRange)
  await createReservation({
    start_date: dateRange.startDate.toISOString().split("T")[0],
    end_date: dateRange.endDate.toISOString().split("T")[0],
    bnb_id: String(selectedBnb?.value?._id),
  });
};
const handleSearch = (searchParams: BnbsSearchType) => {
  searchCriteria = searchParams;
};

const handleBookMeClicked = (bnb: BnbType) => {
  bookMeModalOpen.value = true;
  selectedBnb.value = bnb;
};

onClickOutside(modalRef, () => {
  bookMeModalOpen.value = false;
});

const updateDateRange = (newDateRange: DateRangeType) => {
  dateRange.startDate = newDateRange.start;
  dateRange.endDate = newDateRange.end;
};

</script>

<template>
  <div class="relative bg-black">
    <Navbar />
    <HomepageHero :onSearch="handleSearch" />
    <img
      :src="hotelRoom"
      class="w-screen h-screen object-cover object-bottom opacity-50"
    />
  </div>
  <div class="bg-white p-5 md:p-10">
    <p :class="styles.heading">All Hotels</p>
    <div class="flex flex-col space-y-2 pt-5">
      <div
        v-for="(bnb, index) in bnbs"
        :key="index"
        :class="[
          'grid gap-2 grid-cols-[5fr_1fr] place-items-center justify-items-end',
          { 'border-b border-stone-200': index !== bnbs.length - 1 },
        ]"
      >
        <div class="py-1 grid gap-2 grid-cols-[4fr_2fr_2fr_2fr] w-full">
          <div class="flex flex-col">
            <p :class="twMerge('text-stone-400', styles.paragraph2)">Address</p>
            <p :class="styles.paragraph">{{ bnb?.address }}</p>
          </div>
          <div class="flex flex-col">
            <p :class="twMerge('text-stone-400', styles.paragraph2)">Space</p>
            <p :class="styles.paragraph">{{ bnb?.space }} m<sup>2</sup></p>
          </div>
          <div class="flex flex-col">
            <p :class="twMerge('text-stone-400', styles.paragraph2)">Cost</p>
            <p :class="styles.paragraph">{{ bnb?.cost }} pln/night</p>
          </div>
          <div class="flex flex-col">
            <p :class="twMerge('text-stone-400', styles.paragraph2)">Updated</p>
            <p :class="styles.paragraph">
              {{ moment(bnb?.updatedAt).fromNow() }}
            </p>
          </div>
        </div>
        <Button variant="primary-inverted" @click="handleBookMeClicked(bnb)">
          Book me!
        </Button>
      </div>
      <div
        v-if="bookMeModalOpen"
        ref="modalRef"
        class="p-5 bg-white rounded-lg fixed z-20 top-1/2 left-1/2 transform -translate-y-1/2 -translate-x-1/2 shadow-background"
      >
        <p :class="twMerge('pb-2.5', styles.heading)">Create reservation</p>
        <form @submit.prevent="onSubmit">
          <div class="flex flex-col space-y-2.5">
            <VDatePicker
              v-model.range="dateRange"
              mode="date"
              color="red"
              :minDate="new Date()"
              :date="new Date()"
              :maxDate="new Date(new Date().setDate(new Date().getDate() + 90))"
              @update:modelValue="updateDateRange"
            />
            <Button :isLoading="isCreateReservationPending">
              Confirm reservation
            </Button>
          </div>
        </form>
      </div>
    </div>
  </div>
</template>
